-- TrackingCF PostgreSQL schema

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handle VARCHAR(100) NOT NULL UNIQUE,
    leetcode_handle VARCHAR(100),
    atcoder_handle VARCHAR(100),
    codechef_handle VARCHAR(100),
    avatar_url VARCHAR(500),
    rating INTEGER,
    rank VARCHAR(50),
    last_submission_time TIMESTAMPTZ,
    current_streak INTEGER NOT NULL DEFAULT 0,
    last_streak_date VARCHAR(10),
    rating_history JSONB,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_handle ON users (handle);
CREATE INDEX IF NOT EXISTS idx_users_enabled ON users (enabled);

CREATE TABLE IF NOT EXISTS submissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform VARCHAR(50) NOT NULL DEFAULT 'CODEFORCES',
    contest_id VARCHAR(50) NOT NULL,
    problem_index VARCHAR(10) NOT NULL,
    problem_name VARCHAR(255) NOT NULL,
    rating INTEGER,
    tags JSONB,
    submission_time TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_submission UNIQUE (user_id, contest_id, problem_index)
);

CREATE INDEX IF NOT EXISTS idx_submissions_user_time ON submissions (user_id, submission_time DESC);
CREATE INDEX IF NOT EXISTS idx_submissions_platform_contest ON submissions (platform, contest_id);
CREATE INDEX IF NOT EXISTS idx_submissions_user_rating ON submissions (user_id, rating);
CREATE INDEX IF NOT EXISTS idx_submissions_submission_time ON submissions (submission_time DESC);

CREATE TABLE IF NOT EXISTS user_stats (
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    total_score INTEGER NOT NULL DEFAULT 0,
    count_no_rating INTEGER NOT NULL DEFAULT 0,
    count_800_900 INTEGER NOT NULL DEFAULT 0,
    count_1000 INTEGER NOT NULL DEFAULT 0,
    count_1100 INTEGER NOT NULL DEFAULT 0,
    count_1200_plus INTEGER NOT NULL DEFAULT 0,
    last_calculated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contests (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50),
    phase VARCHAR(50),
    frozen BOOLEAN,
    "durationSeconds" INTEGER,
    "startTimeSeconds" INTEGER,
    "relativeTimeSeconds" INTEGER,
    problems JSONB,
    platform VARCHAR(50) NOT NULL DEFAULT 'CODEFORCES',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_metadata (
    key_name VARCHAR(50) PRIMARY KEY,
    value VARCHAR(255),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admins (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INTEGER REFERENCES admins(id) ON DELETE SET NULL,
    action VARCHAR(50) NOT NULL,
    details JSONB,
    ip_address VARCHAR(45) NOT NULL,
    user_agent VARCHAR(500),
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    related_id VARCHAR(100),
    link VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications (created_at DESC);

CREATE TABLE IF NOT EXISTS chat_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(100) NOT NULL,
    user_handle VARCHAR(100) NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('user', 'model')),
    message TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON chat_messages (session_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_handle ON chat_messages (user_handle);
CREATE INDEX IF NOT EXISTS idx_chat_messages_timestamp ON chat_messages (timestamp);

CREATE OR REPLACE FUNCTION touch_users_last_updated()
RETURNS TRIGGER AS $$
BEGIN
    NEW.last_updated = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION touch_user_stats_last_calculated()
RETURNS TRIGGER AS $$
BEGIN
    NEW.last_calculated = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_last_updated ON users;
CREATE TRIGGER trg_users_last_updated
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION touch_users_last_updated();

DROP TRIGGER IF EXISTS trg_user_stats_last_calculated ON user_stats;
CREATE TRIGGER trg_user_stats_last_calculated
BEFORE UPDATE ON user_stats
FOR EACH ROW EXECUTE FUNCTION touch_user_stats_last_calculated();

DROP TRIGGER IF EXISTS trg_contests_updated_at ON contests;
CREATE TRIGGER trg_contests_updated_at
BEFORE UPDATE ON contests
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

DROP TRIGGER IF EXISTS trg_system_metadata_updated_at ON system_metadata;
CREATE TRIGGER trg_system_metadata_updated_at
BEFORE UPDATE ON system_metadata
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
